[package]
name = "boyan_detector_bot"
version = "0.1.0"
authors = ["Psilon <pzixel@gmail.com>"]
build = "build.rs"

[dependencies]
iron = "*"
bodyparser = "*"
serde_derive = "*"
serde = "*"
serde_json = "*"
hyper = "0.11"
hyper-tls = "0.1"
tokio-core = "0.1"
config = "0.7"
futures = "*"
sha2 = "0.7"
itertools = "0.7"
log = "0.4"
log4rs = { version = "0.4", features = ["toml"] }
