[package]
name = "boyan_detector_bot"
version = "0.1.0"
authors = ["Psilon <pzixel@gmail.com>"]

[dependencies]
bytes = "*"
futures = "0.1.21"
http = "0.1"
hyper = "0.12"
hyper-tls = "0.2"
log = "0.4"
log4rs = { version = "0.8", features = ["toml"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
sha2 = "0.7"
