refresh_rate = "30 seconds"

[appenders]

  [appenders.stdout]
  kind = "console"

[root]
level = "warn"
appenders = [
  "stdout"
]

[loggers]
  [loggers.boyan_detector_bot]
  level = "debug"