max_width = 120
format_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
wrap_comments = true
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
combine_control_expr = true
merge_derives = true
unstable_features = true
error_on_line_overflow = true
error_on_unformatted = true
edition = "2018"
