[package]
name = "imagedb"
version = "0.1.0"
authors = ["Psilon <pzixel@gmail.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
cv = { git = "https://github.com/nebgnahz/cv-rs.git" }