[package]
name = "imagedb"
version = "0.2.0"
authors = ["Psilon <pzixel@gmail.com>"]

[dependencies]
serde = "1.0.67"
serde_json = "1.0.22"
cv = { git = "https://github.com/nebgnahz/cv-rs.git", branch = "feature/multithreaded_hash" }
